// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTrack.DataLayer
{
    public partial class Account
    {
        public Account()
        {
            Transaction = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int TypeId { get; set; }
        public decimal Balance { get; set; }
        public int UserId { get; set; }

        public virtual TypeAccount Type { get; set; } = null!;
        public virtual User User { get; set; } = null!;
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}