// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTrack.DataLayer
{
    public partial class CategoryTransaction
    {
        public CategoryTransaction()
        {
            Transaction = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int Order { get; set; }
        /// <summary>
        /// true - доход, false - расход
        /// </summary>
        public bool Type { get; set; }

        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}