// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FinanceTrack.DataLayer
{
    public partial class TypeAccount
    {
        public TypeAccount()
        {
            Account = new HashSet<Account>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int Order { get; set; }

        public virtual ICollection<Account> Account { get; set; }
    }
}